name: 'Build win64_msvc2019_64'

env:
    QT_VERSION: '5.15.2'
    
on:
    workflow_dispatch:
                
jobs:

    build:
          name: 'Windows 64-bit'
          runs-on: [windows-latest]
          
          config:     
            
            
          env:
            QT_ARCH: 'win64_msvc2019_64'

            
          steps:
          
           - name: 'Cache Qt'
             id: cache-qt
             uses: actions/cache@v1
             with:
                path: ${{ github.workspace }}\..\Qt
                key: ${{ runner.os }}-${{ env.QT_VERSION }}-Qt-Cache
                
           - name: 'Install Qt'
             uses: jurplel/install-qt-action@v2
             with:
               cached: ${{ steps.cache-qt.outputs.cache-hit }}
               version: ${{ env.QT_VERSION }}
               host: 'windows'
               arch: ${{ env.QT_ARCH }}
               dir: 'D:/'
               setup-python: 'false'
               
           - name: 'Add msbuild to PATH'
             uses: microsoft/setup-msbuild@v1.0.2                    
             
           - name: 'Clone repo'
             uses: actions/checkout@v2
             with:
                ref: ${{ env.GITHUB_REF }}
           
           - uses: actions/checkout@v2
           - name: 'Setup tmate session'
             uses: mxschmitt/action-tmate@v3
              
           - name: 'Compile WebPassWare'
             working-directory: ${{ github.workspace }}
             run: |
                qmake.exe WebPassWare.pro                
                
           - name: 'Run tests'
             shell: bash
             working-directory: ${{ github.workspace }}
             run: |
                  ls -l
                  ls -l bin

           - name: 'Set MSVC environment'
             working-directory: ${{ github.workspace }}
             run: |
                "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
