env:
    QT_VERSION: '5.15.2'    

name: Debug session

on:

    repository_dispatch:
        types: [lin_release]
        branches : master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 'Cache Qt'
              id: cache-qt
              uses: actions/cache@v1
              with:
                path: ${{ github.workspace }}/../Qt
                key: ${{ runner.os }}-Qt-${{ env.QT_VERSION }}-Linux-Cache
                
            - name: 'Install Qt'
              uses: jurplel/install-qt-action@v2
              with:
                cached: ${{ steps.cache-qt.outputs.cache-hit }}
                version: ${{ env.QT_VERSION }}
                host: 'linux'
                dir: '${{ github.workspace }}/..'
                
            - name: 'Clone repo'
              uses: actions/checkout@v2
              with:
                ref: ${{ github.event.client_payload.branch }}
                
            - uses: actions/checkout@v2
            - name: 'Setup tmate session'
              uses: mxschmitt/action-tmate@v3
