name: 'CI Windows-64 Relealse'

env:
    QT_VERSION: '5.15.2'
    
on:
    workflow_dispatch:
                
jobs:

  win64: 
          name: 'Windows 64-bit'
          runs-on: [windows-latest]
          env:
            QT_ARCH: 'win64_mingw81'
            MINGW_DIR: ../Qt/Tools/mingw810_64
            QT_BIN_DIR: ../Qt/5.15.2/mingw81_64/bin
            PORTABLE_DIR: output/portable/WebPassWare
            MINGW_URL: https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw/qt.tools.win64_mingw810/8.1.0-1-202004170606x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
            IFW_TOOL_URL: https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_ifw/qt.tools.ifw.42/4.2.0-0-202111080926ifw-win-x86.7z
            IFW_TOOL_DIR: ../Qt/Tools/QtInstallerFramework/4.2/            
            INSTALL_DIR: output/webpassware-installer
            FINAL_EXECUTABLE: 'bin\/webpassware'
            WIZARD_STYLE: 'Modern'
            TARGET_DIR: '\/WebPassWare\/'
            UPDATE_ARCH: 'windows'
            CONFIG_DIR: 'installer/'
            WEBPASSWARE_VERSION: '0.0.2'
            
          steps:
          
           - name: 'Cache Qt'
             id: cache-qt
             uses: actions/cache@v1
             with:
                path: ${{ github.workspace }}\..\Qt
                key: ${{ runner.os }}-${{ env.QT_VERSION }}-Qt-Cache
                
           - name: 'Install Qt'
             uses: jurplel/install-qt-action@v2
             with:
               cached: ${{ steps.cache-qt.outputs.cache-hit }}
               version: ${{ env.QT_VERSION }}
               host: 'windows'
               target: 'desktop'
               install-deps: 'true'
               arch: ${{ env.QT_ARCH }}
               dir: 'D:/'
               setup-python: 'false'
               tools: 'tools_ifw,4.2.0,qt.tools.ifw.42'
        
           - name: 'Install mingw'
             if: steps.cache-qt.outputs.cache-hit != 'true'
             shell: bash
             run: |
                 curl -L ${{ env.MINGW_URL }} --output ../mingw.7z
                 7z x -o"../Qt" ../mingw.7z
                 echo "${{ env.MINGW_DIR }}/bin" >> $GITHUB_PATH
                 
           - name: 'Install ifw_tool'
             if: steps.cache-qt.outputs.cache-hit != 'true'
             shell: bash
             run: |
                 curl -L ${{ env.IFW_TOOL_URL }} --output ../ifw_tool.7z
                 7z x -o"../Qt" ../ifw_tool.7z
                 echo "${{ env.IFW_TOOL_DIR }}/bin" >> $GITHUB_PATH
                 ls -al ${{ env.IFW_TOOL_DIR }}/bin

           - name: 'Clone repo'
             uses: actions/checkout@v2
             with:
                ref: ${{ env.GITHUB_REF }}

           - name: 'Prepare output dir'
             shell: bash
             working-directory: ${{ github.workspace }}
             run: |
                mkdir -p output/build
                                                          
           - name: 'Compile WebPassWare'
             working-directory: ${{ github.workspace }}/output/build
             run: |
                qmake.exe ..\..\WebPassWare.pro
                mingw32-make.exe -j 2
                
           - name: 'Prepare portable dir'
             shell: bash
             working-directory: ${{ github.workspace }}/output
             run: |                             
                mkdir -p portable/WebPassWare
                cp -R build/bin/ portable/WebPassWare/
                
           - name: 'Clean-up portable dir'
             shell: bash
             run: |
                cd ${{ env.PORTABLE_DIR }}
                rm -f *.a
                echo "ABSOLUTE_PORTABLE_DIR=`pwd`" >> $GITHUB_ENV
       
           - name: 'Prepare portable distro (Qt)'
             shell: bash
             working-directory: ${{ env.Qt5_Dir }}
             run: |
                for f in Qt5Core Qt5Gui Qt5Network Qt5Sql Qt5Widgets libgcc_s_seh-1 libstdc++-6 libwinpthread-1; do cp bin/$f.dll "$ABSOLUTE_PORTABLE_DIR/bin/"; done
                cp bin/qt.conf "$ABSOLUTE_PORTABLE_DIR/bin/"
                mkdir -p "$ABSOLUTE_PORTABLE_DIR/bin/plugins/iconengines"
                mkdir -p "$ABSOLUTE_PORTABLE_DIR/bin/plugins/platforms"
                mkdir -p "$ABSOLUTE_PORTABLE_DIR/bin/plugins/styles"
                mkdir -p "$ABSOLUTE_PORTABLE_DIR/bin/plugins/imageformats"
                mkdir -p "$ABSOLUTE_PORTABLE_DIR/bin/plugins/sqldrivers"
                cp plugins/iconengines/qsvgicon.dll "$ABSOLUTE_PORTABLE_DIR/bin/plugins/iconengines"
                cp plugins/platforms/qwindows.dll "$ABSOLUTE_PORTABLE_DIR/bin/plugins/platforms"
                cp plugins/styles/qwindowsvistastyle.dll "$ABSOLUTE_PORTABLE_DIR/bin/plugins/styles"
                for f in qgif qicns qico qjpeg qsvg qtga qtiff qwbmp; do cp plugins/imageformats/$f.dll "$ABSOLUTE_PORTABLE_DIR/bin/plugins/imageformats"; done
                for f in qsqlite qsqlodbc qsqlpsql ; do cp plugins/sqldrivers/$f.dll "$ABSOLUTE_PORTABLE_DIR/bin/plugins/sqldrivers"; done

           - name: 'Prepare portable distro (Resources)'
             shell: bash
             working-directory: ${{ github.workspace }}
             run: |
                cp icons/progicon.ico "$ABSOLUTE_PORTABLE_DIR"/
                cp icons/50px/WebPassWare.png "$ABSOLUTE_PORTABLE_DIR"/

           - name: 'Determine WebPassWare version'
             shell: bash
             working-directory: ${{ github.workspace }}
             run: |
                echo "WEBPASSWARE_VERSION_2=`grep WEBPASSWARE_VERSION CURRENT_VERSION.TXT | cut -d '=' -f 2`" >> $GITHUB_ENV
            
           - name: 'Assemble install package'
             shell: bash
             working-directory: ${{ github.workspace }}
             run: |
                  mkdir -p ${{ env.INSTALL_DIR }}/config/
                  mkdir -p ${{ env.INSTALL_DIR }}/packages/io.qt/data/bin/
                  mkdir -p ${{ env.INSTALL_DIR }}/packages/io.qt/meta/
                  mkdir -p ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/data/bin/
                  mkdir -p ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/meta/
                  
                  cp -a ${{ env.CONFIG_DIR }}/config/*.png ${{ env.INSTALL_DIR }}/config/
                  cp -a ${{ env.CONFIG_DIR }}/config/*.ico ${{ env.INSTALL_DIR }}/config/
                  cp -a ${{ env.CONFIG_DIR }}/config/config.xml ${{ env.INSTALL_DIR }}/config/
                  cp -a ${{ env.CONFIG_DIR }}/config/controller.qs ${{ env.INSTALL_DIR }}/config/
                  cp -a ${{ env.CONFIG_DIR }}/config/style.qss ${{ env.INSTALL_DIR }}/config/
                  cp -a ${{ env.CONFIG_DIR }}/config/qt_package.xml ${{ env.INSTALL_DIR }}/packages/io.qt/meta/package.xml
                  cp -a ${{ env.CONFIG_DIR }}/config/webpassware_package.xml ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/meta/package.xml
                  cp -a ${{ env.CONFIG_DIR }}/config/installscript.qs ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/meta/
                  cp -a ${{ env.CONFIG_DIR }}/config/create_links.ui ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/meta/

           - name: 'Copy data to install package'
             shell: bash
             working-directory: ${{ github.workspace }}
             run: |
                cp -R "$ABSOLUTE_PORTABLE_DIR"/bin/ ${{ env.INSTALL_DIR }}/packages/io.qt/data/
                mv ${{ env.INSTALL_DIR }}/packages/io.qt/data/bin/webpassware.exe ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/data/bin/
                cp -a ${{ env.CONFIG_DIR }}/config/webpassware.png ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/data/
                cp -a ${{ env.CONFIG_DIR }}/config/webpassware.ico ${{ env.INSTALL_DIR }}/packages/pl.com.awsoftware.webpassware/data/
                      
           - name: 'Config install package'
             shell: bash
             working-directory: ${{ env.INSTALL_DIR }}
             run: |
                DATE=`date +%Y-%m-%d`
                sed -i "s/%FINAL_EXECUTABLE%/$FINAL_EXECUTABLE/" config/config.xml
                sed -i "s/%WIZARD_STYLE%/$WIZARD_STYLE/" config/config.xml
                sed -i "s/%TARGET_DIR%/$TARGET_DIR/" config/config.xml
                sed -i "s/%UPDATE_ARCH%/$UPDATE_ARCH/" config/config.xml                
                sed -i "s/%QT_VERSION%/$QT_VERSION/" packages/io.qt/meta/package.xml
                sed -i "s/%DATE%/$DATE/" packages/io.qt/meta/package.xml
                sed -i "s/%WEBPASSWARE_VERSION%/$WEBPASSWARE_VERSION/" packages/pl.com.awsoftware.webpassware/meta/package.xml
                sed -i "s/%DATE%/$DATE/" packages/pl.com.awsoftware.webpassware/meta/package.xml

           - name: 'Assemble install package'             
             shell: bash
             working-directory: ${{ env.INSTALL_DIR }}
             run: |
                  ../../${{ env.IFW_TOOL_DIR }}/bin/binarycreator.exe -f -c config/config.xml -p packages "InstallWebPassWare-0.0.2.exe"
                  ls -al        
            
           - name: 'Assemble portable package'
             shell: bash
             run: |
                  cd $ABSOLUTE_PORTABLE_DIR/..
                  7z a -r webpassware-0.0.2.zip WebPassWare
                  ls -al

           - name: 'Upload package artifact'
             uses: actions/upload-artifact@v1
             with:
                name: webpassware-${{ env.WEBPASSWARE_VERSION }}
                path: output/portable/webpassware-${{ env.WEBPASSWARE_VERSION }}
                
           - name: 'Upload install artifact'
             uses: actions/upload-artifact@v1
             with:
                name: InstallWebPassWare-${{ env.WEBPASSWARE_VERSION }}.exe
                path: ${{ env.INSTALL_DIR }}/InstallWebPassWare-${{ env.WEBPASSWARE_VERSION }}.exe
